# Generated by Django 6.0.4 on 2026-05-04 20:09

import django.db.models.deletion
import dossiers.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierAchat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("depose", "Déposé"),
                            ("en_traitement", "En traitement"),
                            ("valide", "Validé"),
                            ("refuse", "Refusé"),
                        ],
                        default="depose",
                        max_length=20,
                    ),
                ),
                (
                    "cni",
                    models.FileField(
                        upload_to="documents/",
                        validators=[dossiers.models.valider_document],
                    ),
                ),
                (
                    "justificatif_domicile",
                    models.FileField(
                        upload_to="documents/",
                        validators=[dossiers.models.valider_document],
                    ),
                ),
                (
                    "rib",
                    models.FileField(
                        upload_to="documents/",
                        validators=[dossiers.models.valider_document],
                    ),
                ),
                (
                    "justificatif_revenus",
                    models.FileField(
                        upload_to="documents/",
                        validators=[dossiers.models.valider_document],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reprise_vehicule", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DossierLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("depose", "Déposé"),
                            ("en_traitement", "En traitement"),
                            ("valide", "Validé"),
                            ("refuse", "Refusé"),
                        ],
                        default="depose",
                        max_length=20,
                    ),
                ),
                (
                    "cni",
                    models.FileField(
                        upload_to="documents/",
                        validators=[dossiers.models.valider_document],
                    ),
                ),
                (
                    "justificatif_domicile",
                    models.FileField(
                        upload_to="documents/",
                        validators=[dossiers.models.valider_document],
                    ),
                ),
                (
                    "rib",
                    models.FileField(
                        upload_to="documents/",
                        validators=[dossiers.models.valider_document],
                    ),
                ),
                (
                    "justificatif_revenus",
                    models.FileField(
                        upload_to="documents/",
                        validators=[dossiers.models.valider_document],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "duree_mois",
                    models.IntegerField(
                        choices=[
                            (12, "12 mois"),
                            (24, "24 mois"),
                            (36, "36 mois"),
                            (48, "48 mois"),
                        ]
                    ),
                ),
                ("assurance", models.BooleanField(default=False)),
                ("entretien", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vehicule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vehicles.vehicule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
