# Generated by Django 6.0.4 on 2026-05-04 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Marque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Marque",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Vehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modele", models.CharField(max_length=100)),
                ("annee", models.PositiveIntegerField()),
                ("kilometrage", models.PositiveIntegerField()),
                (
                    "motorisation",
                    models.CharField(
                        choices=[
                            ("essence", "Essence"),
                            ("diesel", "Diesel"),
                            ("hybride", "Hybride"),
                            ("electrique", "Électrique"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "loyer_mensuel",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("achat", "Achat"), ("location", "Location")],
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="vehicules/")),
                ("disponible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "marque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicules",
                        to="vehicles.marque",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
