# Generated by Django 6.0.4 on 2026-05-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marque",
            options={"ordering": ["nom"]},
        ),
        migrations.AddField(
            model_name="vehicule",
            name="boite",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="consommation",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="nom_complet",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="portes",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="puissance_din",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="vehicule",
            name="puissance_fiscale",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
