# Generated by Django 6.0.4 on 2026-05-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_alter_marque_options_vehicule_boite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicule",
            name="image_slug",
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
